### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by RodolfoRodriguezMata**

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Good Job team💪
Your project looks fantastic, I could not distinguish it from the original page at a point in time🙂.
Here is a tiny issue we have to fix to get this project approved🙂.
- [ ] Let make all the bottom element align in a row as in the original🙂.
Currently, I get this the output at my end
Screenshot from 2019-11-07 18-02-19
> Please, check your ```.lower-column``` element and try to use a suitable ```percentage %``` instead of having ```width: 195px;```.
## Kindly make this change and submit the project for review
Feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.
#### Happy coding😇

**Comment by shshamim63** [comment]
## Status :taco: Approved :taco: 
___
Hi @RodolfoRodriguezMata  and @mohamedSabry0 :wave: ,
Well done :clap:. Everything looks perfect. Neat and clean code. I will suggest only one thing. That is separating your reset css code. There are many style reset for css. So i believe you should create a separate reset.css file where you should place all your css code that are responsible for styling reset. 
#### This :+1:  is from me. You can merger it and don't forget to fill the project completion form.
## :clubs:  Happy Coding :clubs: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/) | [Slack](Shakhawat Hossain)

**Comment by RodolfoRodriguezMata** [comment]
Thank you very much for your feedback guys!

**Pull request merged**
